name: VRT Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  capture-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install rendering dependencies
        run: sudo apt-get install -y xvfb libgl1-mesa-dri

      - name: Download latest Godot
        run: |
          RELEASE_TAG=$(curl -s "https://api.github.com/repos/godotengine/godot/releases/latest" | jq -r '.tag_name')
          FILENAME="Godot_v${RELEASE_TAG}_linux.x86_64"
          echo "Downloading Godot ${RELEASE_TAG}..."
          wget -q "https://github.com/godotengine/godot/releases/download/${RELEASE_TAG}/${FILENAME}.zip"
          unzip -q "${FILENAME}.zip"
          mv "${FILENAME}" godot
          chmod +x godot

      - name: Capture screenshots
        run: |
          xvfb-run ./godot --rendering-driver opengl3 --fixed-fps 60 --path "$PWD/tests" --script "$PWD/capture.gd"

      - name: Upload screenshots as artifact
        uses: actions/upload-artifact@v7
        with:
          name: vrt-screenshots-linux
          path: tests/vr_screenshots/
          if-no-files-found: error
